const products = [
	{
		id: 'nationalExpress',
		mode: 'train',
		bitmasks: [1],
		name: 'InterCityExpress',
		short: 'ICE',
		vendo: 'ICE',
		ris: 'HIGH_SPEED_TRAIN',
		ris_alt: 'HIGH_SPEED_TRAIN',
		dbnav: 'HOCHGESCHWINDIGKEITSZUEGE',
		dbnav_short: 'ICE',
		default: true,
	},
	{
		id: 'national',
		mode: 'train',
		bitmasks: [2],
		name: 'InterCity & EuroCity',
		short: 'IC/EC',
		vendo: 'EC_IC',
		ris: 'INTERCITY_TRAIN',
		ris_alt: 'INTERCITY_TRAIN',
		dbnav: 'INTERCITYUNDEUROCITYZUEGE',
		dbnav_short: 'IC_EC',
		default: true,
	},
	{
		id: 'regionalExpress',
		mode: 'train',
		bitmasks: [4],
		name: 'RegionalExpress & InterRegio', // FlixTrain??
		short: 'RE/IR',
		vendo: 'IR',
		ris: 'INTER_REGIONAL_TRAIN',
		ris_alt: 'INTER_REGIONAL_TRAIN',
		dbnav: 'INTERREGIOUNDSCHNELLZUEGE',
		dbnav_short: 'IR',
		default: true,
	},
	{
		id: 'regional',
		mode: 'train',
		bitmasks: [8],
		name: 'Regio',
		short: 'RB',
		vendo: 'REGIONAL',
		ris: 'REGIONAL_TRAIN',
		ris_alt: 'REGIONAL_TRAIN',
		dbnav: 'NAHVERKEHRSONSTIGEZUEGE',
		dbnav_short: 'RB',
		default: true,
	},
	{
		id: 'suburban',
		mode: 'train',
		bitmasks: [16],
		name: 'S-Bahn',
		short: 'S',
		vendo: 'SBAHN',
		ris: 'CITY_TRAIN',
		ris_alt: 'CITY_TRAIN',
		dbnav: 'SBAHNEN',
		dbnav_short: 'SBAHN',
		default: true,
	},
	{
		id: 'bus',
		mode: 'bus',
		bitmasks: [32],
		name: 'Bus',
		short: 'B',
		vendo: 'BUS',
		ris: 'BUS',
		ris_alt: 'BUS',
		dbnav: 'BUSSE',
		dbnav_short: 'BUS',
		default: true,
	},
	{
		id: 'ferry',
		mode: 'watercraft',
		bitmasks: [64],
		name: 'Ferry',
		short: 'F',
		vendo: 'SCHIFF',
		ris: 'FERRY',
		ris_alt: 'FERRY',
		dbnav: 'SCHIFFE',
		dbnav_short: 'SCHIFF',
		default: true,
	},
	{
		id: 'subway',
		mode: 'train',
		bitmasks: [128],
		name: 'U-Bahn',
		short: 'U',
		vendo: 'UBAHN',
		ris: 'SUBWAY',
		ris_alt: 'SUBWAY',
		dbnav: 'UBAHN',
		dbnav_short: 'UBAHN',
		default: true,
	},
	{
		id: 'tram',
		mode: 'train',
		bitmasks: [256],
		name: 'Tram',
		short: 'T',
		vendo: 'TRAM',
		ris: 'TRAM',
		ris_alt: 'TRAM',
		dbnav: 'STRASSENBAHN',
		dbnav_short: 'STR',
		default: true,
	},
	{
		id: 'taxi',
		mode: 'taxi',
		bitmasks: [512],
		name: 'Group Taxi',
		short: 'Taxi',
		vendo: 'ANRUFPFLICHTIG',
		ris: 'TAXI',
		ris_alt: 'SHUTTLE',
		dbnav: 'ANRUFPFLICHTIGEVERKEHRE',
		dbnav_short: 'ANRUFPFLICHTIGEVERKEHRE',
		default: true,
	},
];

export {
	products,
};
