const products = [
	{
		id: 'nationalExpress',
		mode: 'train',
		bitmasks: [1],
		name: 'InterCityExpress',
		short: 'ICE',
		vendo: 'ICE',
		default: true,
	},
	{
		id: 'national',
		mode: 'train',
		bitmasks: [2],
		name: 'InterCity & EuroCity',
		short: 'IC/EC',
		vendo: 'EC_IC',
		default: true,
	},
	{
		id: 'regionalExpress',
		mode: 'train',
		bitmasks: [4],
		name: 'RegionalExpress & InterRegio', // FlixTrain??
		short: 'RE/IR',
		vendo: 'IR',
		default: true,
	},
	{
		id: 'regional',
		mode: 'train',
		bitmasks: [8],
		name: 'Regio',
		short: 'RB',
		vendo: 'REGIONAL',
		default: true,
	},
	{
		id: 'suburban',
		mode: 'train',
		bitmasks: [16],
		name: 'S-Bahn',
		short: 'S',
		vendo: 'SBAHN',
		default: true,
	},
	{
		id: 'bus',
		mode: 'bus',
		bitmasks: [32],
		name: 'Bus',
		short: 'B',
		vendo: 'BUS',
		default: true,
	},
	{
		id: 'ferry',
		mode: 'watercraft',
		bitmasks: [64],
		name: 'Ferry',
		short: 'F',
		vendo: 'SCHIFF',
		default: true,
	},
	{
		id: 'subway',
		mode: 'train',
		bitmasks: [128],
		name: 'U-Bahn',
		short: 'U',
		vendo: 'UBAHN',
		default: true,
	},
	{
		id: 'tram',
		mode: 'train',
		bitmasks: [256],
		name: 'Tram',
		short: 'T',
		vendo: 'TRAM',
		default: true,
	},
	{
		id: 'taxi',
		mode: 'taxi',
		bitmasks: [512],
		name: 'Group Taxi',
		short: 'Taxi',
		vendo: 'ANRUFPFLICHTIG',
		default: true,
	},
];

export {
	products,
};
